#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Basel Hindi

# Short bio or description (displayed in the header)
description: DREAM Project - Sports Video Accessibility

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://baselhindi.github.io/images/Basel_Headshot.jpg

#
# Flags below are optional
#


## test section

# Site Author
author:
  name             : "Basel Hindi"
  avatar           : https://baselhindi.github.io/images/Basel_Headshot.jpg
  bio              : "Human-Computer Interaction | Computer Vision | Deep-Learning | Accessibility"
  location         : "New York, USA"
  employer         :
  pubmed           : #"https://www.ncbi.nlm.nih.gov/pubmed/?term=john+snow"
  googlescholar    : ##
  email            : "bh2807@columbia.edu"
  researchgate     :  # example: "https://www.researchgate.net/profile/yourprofile"
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : "baselhindi"
  google_plus      :
  keybase          :
  instagram        :
  impactstory      : #"https://profiles.impactstory.org/u/xxxx-xxxx-xxxx-xxxx"
  lastfm           :
  linkedin         : "basel-hindi-b1a453148"
  orcid            : # "https://orcid.org/0000-0002-9084-9395"
  pinterest        :
  soundcloud       :
  stackoverflow    : # http://stackoverflow.com/users/123456/username
  steam            :
  tumblr           :
  twitter          : #"replacethistwitterhandle"
  vine             :
  weibo            :
  xing             :
  youtube          :
  wikipedia        :




## end of test section






# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: bh2807@columbia.edu
  facebook:
  flickr:
  rss: # just type anything here for a working RSS icon

# Your website URL (e.g. http://ajstent.github.io)
# Used for Sitemap.xml and your RSS feed
url:

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/



# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

theme: jekyll-theme-cayman
